pygments: true
markdown: rdiscount
permalink: pretty

# Booleans for HTML
disqus: true
analytics: true

# For RSS
name: Gaurav Mali
description: Personal website of a software engineering undergrad at University of Waterloo
url: http://gauravmali.com